-- AlterTable
ALTER TABLE "Post" ADD COLUMN "coverImageUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Post" ADD COLUMN "metaTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Post" ADD COLUMN "metaDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Post" ADD COLUMN "publishedAt" DATETIME;
