-- AlterTable
ALTER TABLE "Product" ADD COLUMN "brand" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "quickVerdict" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "whyFeatured" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "highlightsJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Product" ADD COLUMN "bestForJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Product" ADD COLUMN "notForJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Product" ADD COLUMN "finalVerdict" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "editorialNotes" TEXT NOT NULL DEFAULT '';
