import { SAMPLE_EDITORIAL_NOTE } from "../src/lib/editorial";

export type EditorialOverlay = {
  brand: string;
  quickVerdict: string;
  whyFeatured: string;
  highlightsJson: string;
  bestForJson: string;
  notForJson: string;
  finalVerdict: string;
  featuresJson: string;
  editorialNotes: string;
};

const note = SAMPLE_EDITORIAL_NOTE;

function overlay(
  brand: string,
  quickVerdict: string,
  whyFeatured: string,
  highlights: string[],
  bestFor: string[],
  notFor: string[],
  finalVerdict: string,
  specs: Record<string, string>,
): EditorialOverlay {
  return {
    brand,
    quickVerdict,
    whyFeatured,
    highlightsJson: JSON.stringify(highlights),
    bestForJson: JSON.stringify(bestFor),
    notForJson: JSON.stringify(notFor),
    finalVerdict,
    featuresJson: JSON.stringify(specs),
    editorialNotes: note,
  };
}

export const EDITORIAL_BY_SLUG: Record<string, EditorialOverlay> = {
  "airwave-pro-headphones": overlay(
    "AirWave",
    "Best suited for commuters who want listed noise cancelling and about 40 hours between charges.",
    "This is the pair we send most often after a reel: the listing calls out noise cancelling that is meant for a metro ride, and a battery claim that means you are not charging every night. We featured it as a daily-carry headphone, not a studio monitor.",
    ["Listed as wireless ANC", "About 40 hours between charges", "Described as comfortable for long sessions"],
    ["People who commute or sit in noisy rooms", "Anyone who wants fewer charging days"],
    ["Anyone who needs a pair that disappears in a small bag", "Listeners who want wired ANC"],
    "A commuter headphone if the listed ANC and battery matter more than packed size.",
    {
      "Noise cancelling": "Yes (ANC, listed)",
      Battery: "About 40 hours",
      Fit: "Over-ear; bulky in a small bag",
      "Wired ANC": "No",
    },
  ),
  "pixelview-4k-monitor": overlay(
    "PixelView",
    "Best suited for a work-from-home desk that needs sharp 4K text and USB-C laptop charging.",
    "We featured this screen because the listing is a 27-inch 4K IPS panel with USB-C charging — one cable can power a laptop and keep the desk small. It is on the list as a work and edit monitor, not a high-refresh gaming display.",
    ["27-inch 4K IPS, listed", "USB-C charging", "Height-adjustable stand"],
    ["People editing text or photos at a desk", "Anyone who wants USB-C to cut cable clutter"],
    ["Competitive gamers who need more than 60Hz", "Buyers who want built-in speakers"],
    "A clean 4K desk screen if you accept 60Hz and no speakers.",
    {
      Size: "27-inch",
      Resolution: "4K IPS (listed)",
      "Video / refresh": "60Hz only",
      Connectivity: "USB-C charging",
      Stand: "Height-adjustable",
      Speakers: "None listed",
    },
  ),
  "swifttype-mechanical-keyboard": overlay(
    "SwiftType",
    "Best suited for people who want a low-profile wireless mechanical board they can take to a cafe.",
    "We featured it because the listing is a slim, hot-swappable, tri-mode wireless 75% board — the kind of keyboard that stays in a bag between shoots. It is on the list for portable typing, not for a full desktop numpad layout.",
    ["Hot-swappable switches", "Tri-mode wireless", "Compact 75% layout"],
    ["People who type away from a desk", "Anyone who wants to change switches later"],
    ["Anyone who needs a numpad", "Typists who do not want a learning curve after a laptop"],
    "A travel mechanical keyboard if you can live without a numpad.",
    {
      Profile: "Low-profile mechanical",
      Switches: "Hot-swappable",
      Wireless: "Tri-mode",
      Layout: "75% (no numpad)",
    },
  ),
  "novapad-ultra-tablet": overlay(
    "NovaPad",
    "Best suited for notes, storyboards, and watching cuts on a flight — if the OLED screen is the reason to buy.",
    "We featured this tablet because the listing puts an 11-inch OLED panel and a stylus in the box, plus all-day battery. It is on the list as a screen-first slate, not as a laptop replacement with a deep app catalogue.",
    ["11-inch OLED panel", "Stylus included", "All-day battery (listed)"],
    ["People who take handwritten notes or sketch", "Travellers who watch video on a plane"],
    ["Anyone who needs a wide Android app set", "People who still want a headphone jack"],
    "Buy it for the listed OLED and stylus, not for headphone-jack convenience.",
    {
      Size: "11-inch",
      Panel: "OLED (listed)",
      Stylus: "Included",
      Battery: "All-day (listed)",
      "Headphone jack": "No",
    },
  ),
  "brewmaster-elite-coffee": overlay(
    "BrewMaster",
    "Best suited for households that want drip coffee with a built-in grinder and a thermal carafe.",
    "We featured it because the listing combines a burr grinder, a programmable timer, and a thermal carafe — fresh grounds without a second appliance, and no hot plate to cook the pot. It is on the list for a counter that can spare the footprint.",
    ["Built-in burr grinder", "Thermal carafe", "Programmable timer"],
    ["People who drink a pot in the morning", "Anyone who wants grind and brew in one machine"],
    ["Small kitchens that cannot spare the footprint", "Anyone sensitive to a loud grinder"],
    "A one-machine drip setup if you have the counter space and can live with grinder noise.",
    {
      Type: "Drip coffee maker",
      Grinder: "Built-in burr",
      Carafe: "Thermal",
      Timer: "Programmable",
      Footprint: "Large (listed)",
    },
  ),
  "aircrisp-pro-air-fryer": overlay(
    "AirCrisp",
    "Best suited for a family kitchen that wants a 6-quart digital air fryer with simple presets.",
    "This is the kitchen ask we get every week after a reel. The listing is a family-size basket, eight presets, and dishwasher-safe parts. We featured it as a weeknight cooker, not a tiny snack fryer.",
    ["6-quart / family-size basket", "Eight presets", "Dishwasher-safe parts"],
    ["Households cooking a family batch", "People who want presets instead of a manual dial"],
    ["Tiny counters that cannot spare the space", "Anyone who wants something quieter than a microwave"],
    "A family-size air fryer if you have the counter and can live with the noise.",
    {
      Capacity: "6-quart (listed)",
      Controls: "Digital, 8 presets",
      Parts: "Dishwasher-safe (listed)",
      Noise: "Louder than a microwave (listed)",
    },
  ),
  "pureblend-pro-blender": overlay(
    "PureBlend",
    "Best suited for one or two people who want a 900W personal blender with travel cups.",
    "We featured it as a morning-smoothie machine that is not a full-size blender: 900W, a self-clean cycle, two cups in the box, BPA-free. It is on the list for singles and couples, not for family batches.",
    ["900W personal blender", "Self-clean cycle", "Travel cups included", "BPA-free (listed)"],
    ["One or two people making smoothies", "Anyone who wants cups they can take out"],
    ["Families who need a large jug", "Anyone bothered by max-speed noise"],
    "A small 900W blender if you want travel cups and can accept the size and noise limits.",
    {
      Power: "900W (listed)",
      Type: "Personal blender",
      Cleaning: "Self-clean cycle",
      Cups: "Two travel cups included",
      Materials: "BPA-free (listed)",
    },
  ),
  "chefedge-knife-set": overlay(
    "ChefEdge",
    "Best suited for a home cook who wants a 15-piece German steel set that lives in a hardwood block.",
    "We featured it because the listing is German steel with a block and comfortable handles — a daily chef’s knife plus guest pieces. It is on the list as a starter block, not as dishwasher-safe cutlery.",
    ["15-piece German steel set", "Hardwood block included", "Described as holding an edge"],
    ["Home cooks who want a full block on the counter", "People who will hand-wash knives"],
    ["Anyone who wants dishwasher-safe knives", "Kitchens that cannot spare block space"],
    "A block set if you will hand-wash and have the counter for the hardwood block.",
    {
      Pieces: "15",
      Steel: "German steel (listed)",
      Storage: "Hardwood block included",
      Care: "Hand wash only",
    },
  ),
  "zenflow-yoga-mat-pro": overlay(
    "ZenFlow",
    "Best suited for a home-gym floor that needs a 6mm non-slip mat with alignment lines.",
    "This is the first mat we point to after a home-gym reel: 6mm, alignment marks, a carry strap, and a listing that says grip stays decent when you sweat. We featured it as a starter mat, not the thickest cushion on the market.",
    ["6mm thickness", "Alignment lines", "Carry strap included", "Listed as non-slip when damp"],
    ["People starting a home yoga or mat workout", "Anyone who wants alignment marks"],
    ["Anyone who wants the thickest cushion available", "People sensitive to new-mat smell for a few days"],
    "A 6mm alignment mat if you want grip and marks more than extra thickness.",
    {
      Thickness: "6mm",
      Surface: "Non-slip when damp (listed)",
      Marks: "Alignment lines",
      Carry: "Strap included",
    },
  ),
  "powerlift-adjustable-dumbbells": overlay(
    "PowerLift",
    "Best suited for a small room that wants one pair (5–52.5 lb) instead of a full rack.",
    "We featured this pair because the listing replaces a rack: dial the weight, train, put them back on the tray. It is on the list for floor-space savings, not for people who drop dumbbells.",
    ["5–52.5 lb pair", "Quick dial change", "Replaces a full rack"],
    ["Home gyms with little floor space", "People who will change weight between sets"],
    ["Anyone who drops dumbbells", "Buyers who cannot absorb the upfront cost"],
    "One adjustable pair if you will treat them carefully and want to skip a rack.",
    {
      Range: "5–52.5 lb (listed)",
      Change: "Quick dial",
      Space: "Replaces a full rack",
      Care: "Do not drop them (listed)",
    },
  ),
  "pulseband-fitness-tracker": overlay(
    "PulseBand",
    "Best suited for runs and sleep tracking on a GPS band with a listed 7-day battery — not a full smartwatch.",
    "We featured it as a light band you can sweat on: built-in GPS, heart-rate tracking, a work-week battery, and 50m water resistance on the listing. It is on the list for training and sleep, not for a large watch face.",
    ["Built-in GPS", "7-day / week-long battery (listed)", "Heart-rate tracking", "50m water resistance (listed)"],
    ["Runners who want GPS without a phone", "People who care about sleep more than apps"],
    ["Anyone who wants a large watch screen", "People who need rich notifications"],
    "A GPS fitness band if battery and training matter more than a smartwatch screen.",
    {
      GPS: "Built-in (listed)",
      Battery: "About 7 days",
      Tracking: "Heart rate",
      Water: "50m (listed)",
      Screen: "Small (listed)",
    },
  ),
  "flexband-resistance-set": overlay(
    "FlexBand",
    "Best suited for travel or a small room that wants five band levels plus a door-anchor kit.",
    "We featured it as a packable gym: five strengths, door anchor, handles, and ankle straps. It is on the list for warm-ups through heavier rows if you use the levels honestly — not as a premium door system.",
    ["Five resistance levels", "Door anchor, handles, and ankle straps", "Packs in a bag"],
    ["Travellers and small-space workouts", "People who want a full accessory kit"],
    ["Anyone with latex skin irritation", "People who need a heavy-duty door anchor"],
    "A five-level kit if you will pack it and can accept a basic door anchor and latex.",
    {
      Levels: "Five",
      Kit: "Door anchor, handles, ankle straps",
      Pack: "Fits in a bag",
      Material: "Latex (can irritate skin)",
    },
  ),
  "meridian-classic-watch": overlay(
    "Meridian",
    "Best suited for someone who wants an automatic watch with sapphire crystal and a leather strap — no smart features.",
    "We featured it as a quiet everyday watch: automatic movement, sapphire crystal, leather strap, and 100m water resistance on the listing. The point of the pick is that it is not a smartwatch.",
    ["Automatic movement", "Sapphire crystal", "Leather strap", "100m water resistance (listed)"],
    ["People who want a finished look with a shirt or a tee", "Buyers who do not want smartwatch features"],
    ["Anyone who will not wear or wind an automatic", "People who want notifications on their wrist"],
    "A leather automatic if you will wear or wind it and do not want a smartwatch.",
    {
      Movement: "Automatic",
      Crystal: "Sapphire",
      Strap: "Leather",
      Water: "100m (listed)",
      Smart: "No smart features",
    },
  ),
  "voyager-carry-on-backpack": overlay(
    "Voyager",
    "Best suited for flights where you want a 28–35L pack and a TSA laptop sleeve.",
    "This is the bag we put on the list after travel reels: it expands when you overpack, and the listing calls out TSA laptop access without emptying the bag. It is a carry-on pack, not a hip-belt hiking bag.",
    ["28–35L, expands to 35L (listed)", "TSA laptop access", "Water-resistant fabric (listed)"],
    ["People who fly with a laptop", "Anyone who overpacks and needs the extra litres"],
    ["Anyone who wants a hip belt", "People who dislike a bulky look when the bag is full"],
    "A flight pack if TSA laptop access matters more than a slim full-bag silhouette.",
    {
      Volume: "28–35L (expands)",
      Laptop: "TSA sleeve (listed)",
      Fabric: "Water-resistant (listed)",
      "Hip belt": "None",
    },
  ),
  "luxframe-polarized-sunglasses": overlay(
    "LuxFrame",
    "Best suited for everyday and driving wear if you want titanium frames, polarised lenses, and UV400.",
    "We featured them because the listing is light titanium, polarised for driving, UV400, and a hard case in the box. They are on the list as daily glasses, not a sports wrap.",
    ["Titanium frames", "Polarised lenses", "UV400", "Hard case included"],
    ["Drivers who want polarised lenses", "People who want a light everyday frame"],
    ["Anyone who needs a sports wrap", "Buyers who want a wide range of frame styles"],
    "Daily polarised sunglasses if you want UV400 and a light titanium frame, not sport coverage.",
    {
      Frames: "Titanium (listed)",
      Lenses: "Polarised",
      UV: "UV400",
      Case: "Hard case included",
      Shape: "Not a sports wrap",
    },
  ),
  "heritage-leather-wallet": overlay(
    "Heritage",
    "Best suited for a front pocket that needs a slim full-grain bifold with RFID and about eight cards.",
    "We featured this wallet because the listing is full-grain leather, RFID lining, eight cards, two bill slots, and a slim profile. It is on the list as a daily bifold, not as a thick cash stack.",
    ["Full-grain leather", "RFID lining", "Slim bifold", "Eight cards, two bill slots (listed)"],
    ["People who carry a short card stack in a front pocket", "Anyone who wants RFID lining"],
    ["Anyone who carries a thick cash stack", "People who will not condition leather occasionally"],
    "A slim full-grain bifold if you keep the card count down and will condition the leather.",
    {
      Leather: "Full-grain",
      RFID: "Yes (listed)",
      Cards: "Eight",
      Bills: "Two slots",
      Profile: "Slim bifold",
    },
  ),
  "vitamin-c-glow-serum": overlay(
    "",
    "Best suited for a morning routine that wants a 10% vitamin C serum listed to brighten in about four weeks.",
    "This is the bottle from the morning-routine reel. The listing is 10% vitamin C, a lightweight serum finish, 30ml, and a four-week brightening claim. We featured it as a daytime serum — the listing also says it can sting on broken skin and needs SPF.",
    ["10% vitamin C", "Listed to brighten in 4 weeks", "Lightweight serum texture", "30ml"],
    ["People adding a vitamin C step in the morning", "Anyone who wants a light, non-sticky finish"],
    ["Anyone with broken skin that stings", "People who will not wear SPF in the day"],
    "A 10% vitamin C serum if you will use SPF and do not have broken skin.",
    {
      Size: "30ml",
      Actives: "10% Vitamin C",
      Finish: "Serum, lightweight",
      Claim: "Brightens in 4 weeks (listed)",
      Daytime: "Needs SPF (listed)",
    },
  ),
  "matte-lip-crayon-set": overlay(
    "",
    "Best suited for a GRWM routine that wants six transfer-proof nude lip crayons.",
    "This is the set from the GRWM reel: six nudes, crayon format, listed as transfer-proof enough for a commute. We featured it as a nude kit, not a full colour wardrobe — and the listing says it dries lips if you skip balm.",
    ["Six nude shades", "Transfer-proof (listed)", "Crayon format"],
    ["People who wear nudes daily", "Anyone who wants a commute-proof matte"],
    ["Anyone who wants a wide colour range", "People who will not use balm under a drying matte"],
    "A six-nude crayon set if you want transfer-proof mattes and will use balm.",
    {
      Shades: "6 nudes",
      Finish: "Matte",
      Wear: "Transfer-proof (listed)",
      Format: "Crayon",
    },
  ),
};
